/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AchievementAchievement } from './AchievementAchievement';
import { AchievementItem } from './AchievementItem';
import { AchievementRecipe } from './AchievementRecipe';
import { AchievementUpgrade } from './AchievementUpgrade';
import { HttpFile } from '../http/http';

export class AchievementConnections {
    'connectionsFrom': Array<AchievementAchievement>;
    'connectionsTo': Array<AchievementAchievement>;
    'requiredForUpgrades': Array<AchievementUpgrade>;
    'requiredForRecipes': Array<AchievementRecipe>;
    'items': Array<AchievementItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "connectionsFrom",
            "baseName": "connections_from",
            "type": "Array<AchievementAchievement>",
            "format": ""
        },
        {
            "name": "connectionsTo",
            "baseName": "connections_to",
            "type": "Array<AchievementAchievement>",
            "format": ""
        },
        {
            "name": "requiredForUpgrades",
            "baseName": "required_for_upgrades",
            "type": "Array<AchievementUpgrade>",
            "format": ""
        },
        {
            "name": "requiredForRecipes",
            "baseName": "required_for_recipes",
            "type": "Array<AchievementRecipe>",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<AchievementItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AchievementConnections.attributeTypeMap;
    }

    public constructor() {
    }
}

