/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type GiantId = "alph" | "cosma" | "friendly" | "grendaline" | "humbaba" | "lem" | "mab" | "pot" | "spriggan" | "tii" | "zille" ;
