/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GiantSkillPivot } from './GiantSkillPivot';
import { HttpFile } from '../http/http';

export class GiantSkill {
    'id': string;
    'categoryId': string;
    'name': string;
    'group': string;
    'level': number;
    'description': string;
    'pointCost': number;
    'requiresLevel': number;
    'questId': string;
    'reqQuests': Array<string>;
    'createdAt': string;
    'updatedAt': string;
    'pivot': GiantSkillPivot;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "pointCost",
            "baseName": "point_cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "requiresLevel",
            "baseName": "requires_level",
            "type": "number",
            "format": ""
        },
        {
            "name": "questId",
            "baseName": "quest_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "reqQuests",
            "baseName": "req_quests",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": "datetime"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": "datetime"
        },
        {
            "name": "pivot",
            "baseName": "pivot",
            "type": "GiantSkillPivot",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GiantSkill.attributeTypeMap;
    }

    public constructor() {
    }
}

