/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GiantId } from './GiantId';
import { GiantSkill } from './GiantSkill';
import { HttpFile } from '../http/http';

export class GiantDetails {
    'createdAt': Date;
    'description': string;
    'followersName': string;
    'gender': string;
    'id': GiantId;
    'name': string;
    'qualities': string;
    'type': string;
    'updatedAt': Date;
    'skills': Array<GiantSkill>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "followersName",
            "baseName": "followers_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "GiantId",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "qualities",
            "baseName": "qualities",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "skills",
            "baseName": "skills",
            "type": "Array<GiantSkill>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GiantDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

