/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemAchievement } from './ItemAchievement';
import { ItemInhabitant } from './ItemInhabitant';
import { RecipeItem } from './RecipeItem';
import { HttpFile } from '../http/http';

export class ItemConnections {
    'achievements'?: Array<ItemAchievement>;
    'npcs'?: Array<ItemInhabitant>;
    'recipesInput'?: Array<RecipeItem>;
    'recipesOutput'?: Array<RecipeItem>;
    'recipesTool'?: Array<RecipeItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "achievements",
            "baseName": "achievements",
            "type": "Array<ItemAchievement>",
            "format": ""
        },
        {
            "name": "npcs",
            "baseName": "npcs",
            "type": "Array<ItemInhabitant>",
            "format": ""
        },
        {
            "name": "recipesInput",
            "baseName": "recipes_input",
            "type": "Array<RecipeItem>",
            "format": ""
        },
        {
            "name": "recipesOutput",
            "baseName": "recipes_output",
            "type": "Array<RecipeItem>",
            "format": ""
        },
        {
            "name": "recipesTool",
            "baseName": "recipes_tool",
            "type": "Array<RecipeItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemConnections.attributeTypeMap;
    }

    public constructor() {
    }
}

