/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Inhabitant } from './Inhabitant';
import { Item } from './Item';
import { Location } from './Location';
import { HttpFile } from '../http/http';

export class LocationDetailsAllOf {
    'items': Array<Item & any>;
    'npcs': Array<Inhabitant & any>;
    'connectionsFrom': Location & any;
    'connectionsTo': Location & any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Item & any>",
            "format": ""
        },
        {
            "name": "npcs",
            "baseName": "npcs",
            "type": "Array<Inhabitant & any>",
            "format": ""
        },
        {
            "name": "connectionsFrom",
            "baseName": "connections_from",
            "type": "Location & any",
            "format": ""
        },
        {
            "name": "connectionsTo",
            "baseName": "connections_to",
            "type": "Location & any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LocationDetailsAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

