/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LocationInhabitant } from './LocationInhabitant';
import { LocationItem } from './LocationItem';
import { LocationLocation } from './LocationLocation';
import { HttpFile } from '../http/http';

export class LocationConnections {
    'items': Array<LocationItem>;
    'npcs': Array<LocationInhabitant>;
    'connectionsFrom': LocationLocation;
    'connectionsTo': LocationLocation;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<LocationItem>",
            "format": ""
        },
        {
            "name": "npcs",
            "baseName": "npcs",
            "type": "Array<LocationInhabitant>",
            "format": ""
        },
        {
            "name": "connectionsFrom",
            "baseName": "connections_from",
            "type": "LocationLocation",
            "format": ""
        },
        {
            "name": "connectionsTo",
            "baseName": "connections_to",
            "type": "LocationLocation",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LocationConnections.attributeTypeMap;
    }

    public constructor() {
    }
}

