/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GiantId } from './GiantId';
import { HttpFile } from '../http/http';

export class Reward {
    'xp'?: number;
    'currants'?: number;
    'mood'?: number;
    'energy'?: number;
    'giant'?: GiantId;
    'giantFavor'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "xp",
            "baseName": "xp",
            "type": "number",
            "format": ""
        },
        {
            "name": "currants",
            "baseName": "currants",
            "type": "number",
            "format": ""
        },
        {
            "name": "mood",
            "baseName": "mood",
            "type": "number",
            "format": ""
        },
        {
            "name": "energy",
            "baseName": "energy",
            "type": "number",
            "format": ""
        },
        {
            "name": "giant",
            "baseName": "giant",
            "type": "GiantId",
            "format": ""
        },
        {
            "name": "giantFavor",
            "baseName": "giant_favor",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Reward.attributeTypeMap;
    }

    public constructor() {
    }
}

