/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Achievement } from './Achievement';
import { Giant } from './Giant';
import { Inhabitant } from './Inhabitant';
import { Item } from './Item';
import { Location } from './Location';
import { Region } from './Region';
import { Skill } from './Skill';
import { HttpFile } from '../http/http';

export class SearchResults {
    'skills': Array<Skill>;
    'achievements': Array<Achievement>;
    'locations': Array<Location>;
    'regions': Array<Region>;
    'giants': Array<Giant>;
    'items': Array<Item>;
    'inhabitants': Array<Inhabitant>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "skills",
            "baseName": "skills",
            "type": "Array<Skill>",
            "format": ""
        },
        {
            "name": "achievements",
            "baseName": "achievements",
            "type": "Array<Achievement>",
            "format": ""
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<Location>",
            "format": ""
        },
        {
            "name": "regions",
            "baseName": "regions",
            "type": "Array<Region>",
            "format": ""
        },
        {
            "name": "giants",
            "baseName": "giants",
            "type": "Array<Giant>",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Item>",
            "format": ""
        },
        {
            "name": "inhabitants",
            "baseName": "inhabitants",
            "type": "Array<Inhabitant>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchResults.attributeTypeMap;
    }

    public constructor() {
    }
}

