/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AchievementDetails } from './AchievementDetails';
import { RecipeItemsInputInner } from './RecipeItemsInputInner';
import { RecipeItemsOutputInner } from './RecipeItemsOutputInner';
import { RecipeItemsToolInner } from './RecipeItemsToolInner';
import { RecipePivot } from './RecipePivot';
import { SkillDetails } from './SkillDetails';
import { HttpFile } from '../http/http';

export class SkillDetailsRequiredForRecipesInner {
    'id': number;
    'name': string;
    'toolWear': number;
    /**
    * Whether the recipe is accessable to the player
    */
    'learnt'?: SkillDetailsRequiredForRecipesInnerLearntEnum;
    'energyCost': number;
    'xpReward': number;
    /**
    * How long the recipe takes to make
    */
    'waitMs': number;
    /**
    * How many of the recipe can be made at once
    */
    'taskLimit': number;
    'createdAt': Date;
    'updatedAt': Date;
    'tool'?: string;
    'pivot': RecipePivot;
    'itemsTool': Array<RecipeItemsToolInner>;
    'itemsInput': Array<RecipeItemsInputInner>;
    'itemsOutput': Array<RecipeItemsOutputInner>;
    'npcs': Array<SkillDetails>;
    'requiredAchievements': Array<AchievementDetails>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "toolWear",
            "baseName": "tool_wear",
            "type": "number",
            "format": ""
        },
        {
            "name": "learnt",
            "baseName": "learnt",
            "type": "SkillDetailsRequiredForRecipesInnerLearntEnum",
            "format": ""
        },
        {
            "name": "energyCost",
            "baseName": "energy_cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "xpReward",
            "baseName": "xp_reward",
            "type": "number",
            "format": ""
        },
        {
            "name": "waitMs",
            "baseName": "wait_ms",
            "type": "number",
            "format": ""
        },
        {
            "name": "taskLimit",
            "baseName": "task_limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "tool",
            "baseName": "tool",
            "type": "string",
            "format": ""
        },
        {
            "name": "pivot",
            "baseName": "pivot",
            "type": "RecipePivot",
            "format": ""
        },
        {
            "name": "itemsTool",
            "baseName": "items_tool",
            "type": "Array<RecipeItemsToolInner>",
            "format": ""
        },
        {
            "name": "itemsInput",
            "baseName": "items_input",
            "type": "Array<RecipeItemsInputInner>",
            "format": ""
        },
        {
            "name": "itemsOutput",
            "baseName": "items_output",
            "type": "Array<RecipeItemsOutputInner>",
            "format": ""
        },
        {
            "name": "npcs",
            "baseName": "npcs",
            "type": "Array<SkillDetails>",
            "format": ""
        },
        {
            "name": "requiredAchievements",
            "baseName": "required_achievements",
            "type": "Array<AchievementDetails>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SkillDetailsRequiredForRecipesInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SkillDetailsRequiredForRecipesInnerLearntEnum = "0" | "1" ;

