/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GiantId } from './GiantId';
import { HttpFile } from '../http/http';

export class SkillGiantPivot {
    'skillId'?: string;
    'giantId'?: GiantId;
    'primary'?: SkillGiantPivotPrimaryEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "skillId",
            "baseName": "skill_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "giantId",
            "baseName": "giant_id",
            "type": "GiantId",
            "format": ""
        },
        {
            "name": "primary",
            "baseName": "primary",
            "type": "SkillGiantPivotPrimaryEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SkillGiantPivot.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SkillGiantPivotPrimaryEnum = "0" | "1" ;

