/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpgradeConditionQuest {
    'questId'?: string;
    'type': UpgradeConditionQuestTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "questId",
            "baseName": "quest_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UpgradeConditionQuestTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpgradeConditionQuest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type UpgradeConditionQuestTypeEnum = "6" ;

