/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpgradeAchievement } from './UpgradeAchievement';
import { UpgradeSkill } from './UpgradeSkill';
import { UpgradeUpgrade } from './UpgradeUpgrade';
import { HttpFile } from '../http/http';

export class UpgradeConnections {
    'requiredSkills': Array<UpgradeSkill>;
    'requiredAchievements': Array<UpgradeAchievement>;
    'requiredUpgrades': Array<UpgradeUpgrade>;
    'requiredForSkills': Array<UpgradeSkill>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "requiredSkills",
            "baseName": "required_skills",
            "type": "Array<UpgradeSkill>",
            "format": ""
        },
        {
            "name": "requiredAchievements",
            "baseName": "required_achievements",
            "type": "Array<UpgradeAchievement>",
            "format": ""
        },
        {
            "name": "requiredUpgrades",
            "baseName": "required_upgrades",
            "type": "Array<UpgradeUpgrade>",
            "format": ""
        },
        {
            "name": "requiredForSkills",
            "baseName": "required_for_skills",
            "type": "Array<UpgradeSkill>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpgradeConnections.attributeTypeMap;
    }

    public constructor() {
    }
}

