/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Achievement } from './Achievement';
import { Skill } from './Skill';
import { Upgrade } from './Upgrade';
import { HttpFile } from '../http/http';

export class UpgradeDetailsAllOf {
    'requiredSkills': Array<Skill & any>;
    'requiredAchievements': Array<Achievement & any>;
    'requiredUpgrades': Array<Upgrade & any>;
    'requiredForSkills': Array<Skill & any>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "requiredSkills",
            "baseName": "required_skills",
            "type": "Array<Skill & any>",
            "format": ""
        },
        {
            "name": "requiredAchievements",
            "baseName": "required_achievements",
            "type": "Array<Achievement & any>",
            "format": ""
        },
        {
            "name": "requiredUpgrades",
            "baseName": "required_upgrades",
            "type": "Array<Upgrade & any>",
            "format": ""
        },
        {
            "name": "requiredForSkills",
            "baseName": "required_for_skills",
            "type": "Array<Skill & any>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpgradeDetailsAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

