/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpgradeRewardKeepable {
    /**
    * number of keepables rewarded
    */
    'num': number;
    'type': UpgradeRewardKeepableTypeEnum;
    'classId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "num",
            "baseName": "num",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UpgradeRewardKeepableTypeEnum",
            "format": ""
        },
        {
            "name": "classId",
            "baseName": "class_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpgradeRewardKeepable.attributeTypeMap;
    }

    public constructor() {
    }
}


export type UpgradeRewardKeepableTypeEnum = "8" ;

