/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpgradeConditionLevel {
    'type': UpgradeConditionLevelTypeEnum;
    'level'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "UpgradeConditionLevelTypeEnum",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpgradeConditionLevel.attributeTypeMap;
    }

    public constructor() {
    }
}


export type UpgradeConditionLevelTypeEnum = "2" ;

