/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpgradeRewardKeepable } from './UpgradeRewardKeepable';
import { UpgradeRewardLearning } from './UpgradeRewardLearning';
import { UpgradeRewardMovement } from './UpgradeRewardMovement';
import { HttpFile } from '../http/http';

export class UpgradeReward {
    'type': UpgradeRewardTypeEnum;
    /**
    * Represents walking speed
    */
    'vxMax': number;
    'gravity': number;
    'vyJump': number;
    'can3Jump': boolean;
    'canWallJump': boolean;
    'multiplier3Jump': number;
    /**
    * number of keepables rewarded
    */
    'num': number;
    'classId': string;

    static readonly discriminator: string | undefined = "type";

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "UpgradeRewardTypeEnum",
            "format": ""
        },
        {
            "name": "vxMax",
            "baseName": "vx_max",
            "type": "number",
            "format": ""
        },
        {
            "name": "gravity",
            "baseName": "gravity",
            "type": "number",
            "format": ""
        },
        {
            "name": "vyJump",
            "baseName": "vy_jump",
            "type": "number",
            "format": ""
        },
        {
            "name": "can3Jump",
            "baseName": "can_3_jump",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canWallJump",
            "baseName": "can_wall_jump",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "multiplier3Jump",
            "baseName": "multiplier_3_jump",
            "type": "number",
            "format": ""
        },
        {
            "name": "num",
            "baseName": "num",
            "type": "number",
            "format": ""
        },
        {
            "name": "classId",
            "baseName": "class_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpgradeReward.attributeTypeMap;
    }

    public constructor() {
        this.type = "UpgradeReward";
    }
}


export type UpgradeRewardTypeEnum = "9" ;

