/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpgradeConditionUpgrade {
    'type': UpgradeConditionUpgradeTypeEnum;
    'imaginationId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "UpgradeConditionUpgradeTypeEnum",
            "format": ""
        },
        {
            "name": "imaginationId",
            "baseName": "imagination_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpgradeConditionUpgrade.attributeTypeMap;
    }

    public constructor() {
    }
}


export type UpgradeConditionUpgradeTypeEnum = "3" ;

