/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSkillAllOfPivot } from './UserSkillAllOfPivot';
import { HttpFile } from '../http/http';

export class UserSkillAllOf {
    'pivot': UserSkillAllOfPivot;
    /**
    * Indicates whether a user has learned the skill.
    */
    'learned': UserSkillAllOfLearnedEnum;
    'starts': string;
    'ends': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pivot",
            "baseName": "pivot",
            "type": "UserSkillAllOfPivot",
            "format": ""
        },
        {
            "name": "learned",
            "baseName": "learned",
            "type": "UserSkillAllOfLearnedEnum",
            "format": ""
        },
        {
            "name": "starts",
            "baseName": "starts",
            "type": "string",
            "format": "datetime"
        },
        {
            "name": "ends",
            "baseName": "ends",
            "type": "string",
            "format": "datetime"
        }    ];

    static getAttributeTypeMap() {
        return UserSkillAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}


export type UserSkillAllOfLearnedEnum = "0" | "1" ;

