/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Category } from './Category';
import { Location } from './Location';
import { Skill } from './Skill';
import { Upgrade } from './Upgrade';
import { HttpFile } from '../http/http';

export class User {
    'avatarImage': string;
    'createdAt': Date;
    'energy': number;
    /**
    * Identifier for the User Model
    */
    'id': number;
    'lastAchievement'?: Category;
    'lastLocation'?: Location;
    'lastLogin': Date;
    'lastSeenSocial': string;
    'lastSkill'?: Skill;
    'lastUpgrade'?: Upgrade;
    'level': number;
    'locationId': string;
    'mood': number;
    'name': string;
    'registered'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "avatarImage",
            "baseName": "avatarImage",
            "type": "string",
            "format": "url"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "energy",
            "baseName": "energy",
            "type": "number",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastAchievement",
            "baseName": "last_achievement",
            "type": "Category",
            "format": ""
        },
        {
            "name": "lastLocation",
            "baseName": "last_location",
            "type": "Location",
            "format": ""
        },
        {
            "name": "lastLogin",
            "baseName": "last_login",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastSeenSocial",
            "baseName": "last_seen_social",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastSkill",
            "baseName": "last_skill",
            "type": "Skill",
            "format": ""
        },
        {
            "name": "lastUpgrade",
            "baseName": "last_upgrade",
            "type": "Upgrade",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "locationId",
            "baseName": "location_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "mood",
            "baseName": "mood",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "registered",
            "baseName": "registered",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}

