/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Achievement } from './Achievement';
import { HttpFile } from '../http/http';

export class AchievementAchievementConnection {
    'achievementId'?: Achievement;
    'connectionId'?: Achievement;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "achievementId",
            "baseName": "achievement_id",
            "type": "Achievement",
            "format": ""
        },
        {
            "name": "connectionId",
            "baseName": "connection_id",
            "type": "Achievement",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AchievementAchievementConnection.attributeTypeMap;
    }

    public constructor() {
    }
}

