/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Recipe } from './Recipe';
import { HttpFile } from '../http/http';

export class AchievementRecipePivot {
    'achievementId'?: string;
    'recipeId'?: Recipe;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "achievementId",
            "baseName": "achievement_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipeId",
            "baseName": "recipe_id",
            "type": "Recipe",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AchievementRecipePivot.attributeTypeMap;
    }

    public constructor() {
    }
}

