/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemAchievement } from './ItemAchievement';
import { ItemInhabitant } from './ItemInhabitant';
import { RecipeItem } from './RecipeItem';
import { HttpFile } from '../http/http';

export class ItemDetails {
    'adjustedScale'?: number;
    'article': ItemDetailsArticleEnum;
    'baseCost': number;
    'capacity': number;
    'categoryId': string;
    'createdAt': Date;
    'description': string;
    'hasInfo': number;
    'hasInfopage': number;
    'id': string;
    'isRoutable': number;
    'label': string;
    'name': string;
    'namePlural': string;
    'nameSingle': string;
    'parentClasses': Array<string>;
    'stackmax': number;
    'updatedAt': Date;
    'achievements': Array<ItemAchievement>;
    'npcs': Array<ItemInhabitant>;
    'recipesInput': Array<RecipeItem>;
    'recipesOutput'?: Array<RecipeItem>;
    'recipesTool': Array<RecipeItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "adjustedScale",
            "baseName": "adjusted_scale",
            "type": "number",
            "format": ""
        },
        {
            "name": "article",
            "baseName": "article",
            "type": "ItemDetailsArticleEnum",
            "format": ""
        },
        {
            "name": "baseCost",
            "baseName": "base_cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "capacity",
            "baseName": "capacity",
            "type": "number",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasInfo",
            "baseName": "has_info",
            "type": "number",
            "format": ""
        },
        {
            "name": "hasInfopage",
            "baseName": "has_infopage",
            "type": "number",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isRoutable",
            "baseName": "is_routable",
            "type": "number",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "namePlural",
            "baseName": "name_plural",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameSingle",
            "baseName": "name_single",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentClasses",
            "baseName": "parent_classes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "stackmax",
            "baseName": "stackmax",
            "type": "number",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "achievements",
            "baseName": "achievements",
            "type": "Array<ItemAchievement>",
            "format": ""
        },
        {
            "name": "npcs",
            "baseName": "npcs",
            "type": "Array<ItemInhabitant>",
            "format": ""
        },
        {
            "name": "recipesInput",
            "baseName": "recipes_input",
            "type": "Array<RecipeItem>",
            "format": ""
        },
        {
            "name": "recipesOutput",
            "baseName": "recipes_output",
            "type": "Array<RecipeItem>",
            "format": ""
        },
        {
            "name": "recipesTool",
            "baseName": "recipes_tool",
            "type": "Array<RecipeItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemDetails.attributeTypeMap;
    }

    public constructor() {
    }
}


export type ItemDetailsArticleEnum = "a" | "the" ;

