/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpgradeRewardMovement {
    'can3Jump': boolean;
    'canWallJump': boolean;
    'gravity': number;
    'multiplier3Jump': number;
    'type': UpgradeRewardMovementTypeEnum;
    /**
    * Represents walking speed
    */
    'vxMax': number;
    'vyJump': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "can3Jump",
            "baseName": "can_3_jump",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "canWallJump",
            "baseName": "can_wall_jump",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "gravity",
            "baseName": "gravity",
            "type": "number",
            "format": ""
        },
        {
            "name": "multiplier3Jump",
            "baseName": "multiplier_3_jump",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "UpgradeRewardMovementTypeEnum",
            "format": ""
        },
        {
            "name": "vxMax",
            "baseName": "vx_max",
            "type": "number",
            "format": ""
        },
        {
            "name": "vyJump",
            "baseName": "vy_jump",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpgradeRewardMovement.attributeTypeMap;
    }

    public constructor() {
    }
}


export type UpgradeRewardMovementTypeEnum = "1" ;

