/**
 * Odd Giants Public API
 * Odd Giants Public API
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ustice@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSkillConnection } from './UserSkillConnection';
import { UserSkillPivot } from './UserSkillPivot';
import { HttpFile } from '../http/http';

export class UserSkill {
    'categoryId'?: string;
    'createdAt'?: string;
    'description'?: string;
    'group'?: string;
    'id'?: string;
    'learned'?: number;
    'level'?: number;
    'name'?: string;
    'pivot'?: UserSkillConnection;
    'pointCost'?: number;
    'questId'?: string;
    'reqQuests'?: Array<string>;
    'requiresLevel'?: number;
    'skillId'?: string;
    'updatedAt'?: string;
    'ends': string;
    'starts': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": "datetime"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "learned",
            "baseName": "learned",
            "type": "number",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "pivot",
            "baseName": "pivot",
            "type": "UserSkillConnection",
            "format": ""
        },
        {
            "name": "pointCost",
            "baseName": "point_cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "questId",
            "baseName": "quest_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "reqQuests",
            "baseName": "req_quests",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "requiresLevel",
            "baseName": "requires_level",
            "type": "number",
            "format": ""
        },
        {
            "name": "skillId",
            "baseName": "skill_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": "datetime"
        },
        {
            "name": "ends",
            "baseName": "ends",
            "type": "string",
            "format": "datetime"
        },
        {
            "name": "starts",
            "baseName": "starts",
            "type": "string",
            "format": "datetime"
        }    ];

    static getAttributeTypeMap() {
        return UserSkill.attributeTypeMap;
    }

    public constructor() {
    }
}



